[package]
name = "cli"
version = "0.1.0"
edition = "2024"
default-run = "cli"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
clap = { version = "4.4.11", features = ["derive"] }
humantime = "2.1.0"
portpicker = "0.1.1"
raw_sync = "0.1.5"
